#! /bin/sh
#
# This file is part of the Code::Blocks IDE and licensed under the GNU General Public License, version 3
# http://www.gnu.org/licenses/gpl-3.0.html
#

CB_DEVEL=devel$1
CB_OUTPUT=output$1
CB_DEVEL_RESDIR=$CB_DEVEL/share/codeblocks
CB_OUTPUT_RESDIR=$CB_OUTPUT/share/codeblocks

mkdir -p ../../../${CB_DEVEL_RESDIR}/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../${CB_OUTPUT_RESDIR}/images/settings > /dev/null 2> /dev/null
cp ./resources/images/*.png ../../../${CB_DEVEL_RESDIR}/images/settings/ > /dev/null 2> /dev/null
cp ./resources/images/*.png ../../../${CB_OUTPUT_RESDIR}/images/settings/ > /dev/null 2> /dev/null
exit 0
