#!/bin/bash
CB_DEVEL=devel$1
CB_OUTPUT=output$1
CB_DEVEL_RESDIR=$CB_DEVEL/share/codeblocks
CB_OUTPUT_RESDIR=$CB_OUTPUT/share/codeblocks
mkdir -p ../../../${CB_OUTPUT}
zip -j9 ../../../${CB_DEVEL_RESDIR}/codesnippets.zip ./manifest.xml
mkdir -p  ../../../${CB_DEVEL_RESDIR}/images/codesnippets > /dev/null 2> /dev/null
mkdir -p ../../../${CB_OUTPUT_RESDIR}/images/codesnippets > /dev/null 2> /dev/null
cp ./resources/*.png ../../../${CB_DEVEL_RESDIR}/images/codesnippets/ > /dev/null 2> /dev/null
cp ./resources/*.png ../../../${CB_OUTPUT_RESDIR}/images/codesnippets/ > /dev/null 2> /dev/null
exit 0
