#!/bin/bash
CB_DEVEL=devel$1
CB_OUTPUT=output$1
CB_DEVEL_RESDIR=$CB_DEVEL/share/codeblocks
CB_OUTPUT_RESDIR=$CB_OUTPUT/share/codeblocks
mkdir -p ../../../${CB_OUTPUT}
zip -j9 ../../../${CB_DEVEL_RESDIR}/codesnippets.zip ./manifest.xml
exit 0
